---
abstract: 'Command-line utility to grep UnicodeData.txt'
author:
  - '唐鳳 <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Uni
name: App-Uni
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  homepage: http://github.com/audreyt/app-uni/tree
  repository:
    type: git
    url: git://github.com/audreyt/app-uni.git
    web: http://github.com/audreyt/app-uni/tree
version: 8
